### ISSUE TITLE
Crash while loading modpack

### ISSUE THREAD

**Issue by Avalonzo** [adam9899/Issues#164]
Hello, I was playing the pack fine and updated the pack yesterday and was again fine and now today the pack constantly crashes during the loading of the pack.

https://paste.dimdev.org/ayomofolor.mccrash

**Comment by ByteTemplar** [comment]
There looks like to be broken .json files, maybe somehow corrupted?
`Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $`

Maybe try redownloading first.
If that doesnt work, then create new instance for the modpack, test it loads and then move savegame there and try load it again.

**REMEMBER to have backups!!**
