### ISSUE TITLE
[1.3.4]Player shop can't be automated, not in a good way anyway

### ISSUE THREAD

**Issue by algul** [adam9899/Issues#260]
There are 2 different way rewards for quests are done. Some quest reward actual money and other reward "coin" items. The actual money reward can't be auto-claimed at all and the "coin item" reward goes into your inventory where you have to "use it" to get the money and also it spams the "reward collected!" box in the top right corner.
I would suggest adding another tier of the quest with much higher item requirements with higher reward, that would be much more practical imo. My mob farm generates bones/flesh and such in high quantities so I complete one quest every 2s or so.

**Comment by ByteTemplar** [comment]
Yes, the coins are spawned directly to players inventory, I resolved this by using Player inventory access block and pipe out coins to a chest.

But the spam is too much from finished quest, so I only sell semi-manually now, if I need currency.

**Comment by ghost** [comment]
It's a mess. I created an issue at FTB Quests. I'm *not* submitting 3.5 million coins in quests manually.
https://github.com/FTBTeam/FTB-Quests/issues/382

**Comment by adam9899** [comment]
This is not an issue with FTB Quests. This is an intended mechanic. The currency is placed within your inventory, you can use the items to add balance. If you leave the automated setup running by selling x32 blocks of diamonds you are rewarded 5000 currency per second per token. If you clicked tokens for 60 seconds you can add 300000 coins to your balance, it's not that difficult or tedious to add balance using the currency in item form. This is an additional mod we've added and nothing to do with FTB quests. If you feel its this big an issue I'd like a followup.

**Comment by adam9899** [comment]
Not to mention you can shift-click stacks to add all to balance.

**Comment by adam9899** [comment]
Toasts on repeatable quests will be disabled moving forward ^

**Comment by ghost** [comment]
Well, I started up and resumed my building and my almost full inventory started filling with coins. I rushed to try to set up a hopper on a quest chest to see if I could pump them somewhere safe, but I couldn't see JEI through all the toasts. In the end I broke the chests. Then I just shut down.

The alternative seemed to be setting up redstone controls and only pumping in stuff when I could spend time doing nothing. Not a good mechanic.

I've considered removing the coin mod, but I was concerned that it could cause other problems and the load time is so long already.

Anyway, try running some stuff from cloches to the quest chest and see how long you can play with your inventory filling ~and the toasts flooding~.

EDIT: Removing the toasts on the repeatable quests is a good idea. They're not really telling you anything anyway.

**Comment by ByteTemplar** [comment]
Like I earlier posted, you can easily setup system to pump out coins from your inventory automatically, it worked nicely, but I also couldnt take the toast notification spam, so stopped using it till upcoming change (I guess I could do it manually myself if wanted).

**Comment by algul** [comment]
I have manually added higher tier of mob drop quests and disabled toast on rewards. That, with the player interface suggestion worked good. I also added recipes to combine lesser coins into greater ones and now it's all fine.

**Comment by adam9899** [comment]
Good suggestions. I'll keep that in mind for the next version.

**Comment by ghost** [comment]
@ByteTemplar I'm glad that's working for you. I'm still concerned about problems with a full inventory and setting up a system to work around a problematic mechanic. This brings me back to my original premise that it's an FTB Quests issue that we can't deal with the quest award mechanic through the quest award system.

So far I've found 3 items in the pack that can route out of the player's inventory. One requires a nether star, one requires AA empowered diamantine, and one requires a running EU2 powergrid and setup. While the EU2 one is on par with the need for access, it also requires playing a specific mod. A mod that's got bugs and isn't to everyone's taste.

IMHO, making players click items for an automated process that adds to a meta value isn't a useful mechanic. At best it's tedious. At worst it's forcing people to play a certain way or deal with the consequences. I don't play Botania because I don't like being forced to play a certain way. I don't do much with EU2 for similar reasons related to the buggy power grid mechanic.

**Comment by 4rz0** [comment]
You should mention the "click/shiftclick to deposit coins" thing in your player shop quest tree.
I also recommend adding recipes to craft coins into their higher/lower tiers.
