### ISSUE TITLE
MC eternal

### ISSUE THREAD

**Issue by Bubblewaffless** [adam9899/Issues#664]
We recently got a server for this modpack using bisect hosting, played for roughly 2 days and then  we got a weird bug. We noticed how when we try to break blocks, nothing drops.  we tried a lot of things, but nothings working. please help, thanks

**Comment by ogradyjd** [comment]
Dude, you have to give the dev more than that.  Error messages?  Version numbers?  Anything?  Developers aren't psychic. 

It sounds like you have major lag. That's common if you have a server with not enough memory or too many chunkloads or chunkloads with high tick-count builds, or a combination of all three.   A server should probably have at _least_ 8GB, since this is a kitchen-sink mod pack.  With more than a few people on it, I wouldn't use less than 10GB.  

That said, you can weed out bad actors by using Lag Goggles.  It's in the pack, so all you have to do is set the keys for it under Controls like you do any other key-binding, and then take a stroll around everyone's bases to see who's got crimson red chunks.  Then you can figure out what they built that is killing your server.   If that's not the case, then it's probably the memory above.

The only other thing I can tell you is to read through issue #628.   If you effectively disable the Hats mod it says there, you'll probably get some performance back.  It might even solve your problem right there.

**Comment by Bubblewaffless** [comment]
Yeah okay I’ll try the things you mentioned, I’m really new to all of this kind of stuff so I’m a little lost lol. But thank you, I’ll give it a try and see what happens

**Comment by Bubblewaffless** [comment]
Yeah okay I’ll look into it, I’m relatively new to server hosting so I’m a bit lost on how to work everything out but thanks for reaching out. The package we have is the 3 gigabyte package and we have 5 people on the server. So I assume that it’s too much for it to handle and I’m gonna look into upgrading it but before so I’m gonna try out those lag goggles you spoke of. Again thanks for helping me out

**Comment by ogradyjd** [comment]
@Bubblewaffless I'd start with more memory.  Up it to at least 6GB, 8GB if you can.  That will get you immediately up and running.  Then use the Lag Goggles to police the builds of your denizens.   Some builds are really, really bad for servers.

**Comment by Bubblewaffless** [comment]
Yeah okay, I’m probably gonna go with the 7 Gb package. Hopefully this will fix it because in game whenever we have issues it hasn’t been saying that there’s errors it’s just that the world has been slowly “Dying”. Weird blocks that are completely invisible show up in our base that we can’t remove and as I said we don’t have tile drops all the sudden. I’ll close this “issue” if it ends up fixing it

**Comment by ogradyjd** [comment]
@adam9899 - I've done extensive testing, and even if most of the lag and memory questions here aren't directly caused by the Hats mod, they are most certainly caused by some interaction between hats and Fish's Undead Rising. 

Once I completely disabled hats, my client and server have been running for several days with no lag, and the client FPS has been steady at 40fps.  Before I had disabled Hats, Everything would last a few hours and then I'd start hitting lag storms which would eventually grow worse until I'd have to restart both server and client.

I don't have time to attach a JVM analyzer onto both server and client and figure out which specific classes or entities are the direct cause, but that's something that the mod authors should deal with.  for you, removing Hats would probably cut way down on most of the extraneous "My serverz - they lagz!!" issues.   I'd rather see you have more time for cool updates to the pack then to have to wade through all these issues caused by a mod that is decorative only. 

Anyway, there's my take.  Love your pack.  Thanks for all the hard work.  I'm working on my own world while watching Direwolf20 playing through it.  Maybe at some point you could include one of these in the pack?  I've been playing with them included for over a month and they haven't cause any issues:

Bonsai Trees 2
Dark Utilities
Draconic Evolution
Environmental Tech
ET Lunar
Project Intelligence (for draconic and enderIO docu)
Quantum Storage
Reliquary v1.3
Torchmaster
Woot
