### ISSUE TITLE
Applied Energistics 2 auto crafting not compatible with Mekanism

### ISSUE THREAD

**Issue by upstairscoffee5** [adam9899/Issues#805]
I've been messing around with AE2's crafting with interfaces and no recipes involving Mekanism seem to work. For example, you can make compressed redstone using redstone dust, but you cannot then use the compressed redstone to make enriched alloy. Although you can craft Mekanism items using the Molecular assembler, you cannot use machines if the recipe involves an item from Mekanism.

**Comment by zhenil** [comment]
This is because compressed redstone are "extras" and can only be inputted in the purple colored slot 
![image](https://user-images.githubusercontent.com/59321403/91525399-fb7b7f00-e933-11ea-9733-37a41151ef78.png)
You'll need to configure which side you want to use to input "extras" via the side configuration tab. You can use this setup:
Interface -> chest -> filter "extras" to enter the side you've configured while other items are inputted in the "regular input" (red color)

**Comment by upstairscoffee5** [comment]
oh my god tysm, feel stupid now lol

**Comment by upstairscoffee5** [comment]
I'm confused as to how this could be executed with AE2 autocrafting though. Since you can't split a recipe between two ME interfaces, or am I missing something?

**Comment by zhenil** [comment]
Instead of directly placing the ME interface to the machine, place a chest as a buffer where the interface will store the items and use conduits/item ducts with filters/servos to pull out the items and input them to the specified sides

**Comment by upstairscoffee5** [comment]
Worked! TY
